### ISSUE TITLE
AllowedApps & Specific Path

### ISSUE THREAD

**Issue by shivadiva** [wiresock/WireSockUI#11]
Hi there.
For me, using a specific path instead of just the process name (without .exe) doesn't work at all.

If I edit the config file within WireSock UI, it won't let me save it as soon as I add .exe to a process name or add a full path.
It also doesn't work when I edit the config file first before importing it.

Any idea how I can solve this issue?

The reason I'm asking is because I have multiple browsers installed. For example, I have both Brave AND Brave Beta installed. But I only want to tunnel Brave Beta, not both Brave browsers. The problem is, the process for both is the same: brave.exe

By the way I'm using Windows 11 Enterprise 22H2 and the latest WireSock 1.2.23.1.

[Screenshots](https://imgur.com/a/njVVyWd)

**Comment by shivadiva** [comment]
Never mind, lol. I figured it out. The solution was the most obvious one: remove the "quotation marks".
It still wouldn't let me save it. I had to manually edit the configuration file first and then import it. Now it's working perfectly!

**Comment by RileyXX** [comment]
Would be nice if we could edit the paths for `DisallowedApps` inside WireSockUI itself rather than having to open the configs manually in a text editor. Hopefully this can be implemented at some point.
