### ISSUE TITLE
Application doesn't quit

### ISSUE THREAD

**Issue by kuitog** [wiresock/WireSockUI#22]
When selecting WiresockUI on the windows taskbar, right click, exit -> The GUI exits.
But the background process remains open and if trying to launch the GUI again it doens't allow it as the process is already running.
Have to manually kill the bg task from task manager in order to restore the GUI.

**Comment by RileyXX** [comment]
That's odd I'm not seeing the same behavior. When I click exit it closes as expected and my connection returns to normal. Perhaps there is an app or process causing it to hang?

**Comment by kuitog** [comment]
This doesn't happen anymore in v0.15 just released. So fixed thanks

**Comment by kuitog** [comment]
This doesn't happen anymore in v0.15 just released. So fixed thanks
