### ISSUE TITLE
AllowedApps special characters

### ISSUE THREAD

**Issue by Iftuga** [wiresock/WireSockUI#28]
Some applications have special characters in their names, and such applications can not be added to AllowedApps

Maybe it could be fixed if applications were to be specified with " symbol around them, e.g., "osu!"
_(Just an idea, I am not sure if it would be possible to implement it that way)_

![image](https://github.com/wiresock/WireSockUI/assets/38592556/10d506b4-0a09-45ec-b94e-ab15576f6832)

![image](https://github.com/wiresock/WireSockUI/assets/38592556/e0b67c39-8217-426b-86b0-d645c48da800)

**Comment by RileyXX** [comment]
Try editing it in text editor instead. You can also try adding the full path to the .exe file instead if the first method doesn't work.

That prompt window is a little buggy, it wont let you save changes in some situations (like when you add full path) even though its supported. It's just a minor issue that will hopefully get patched in a future update.

**Comment by Iftuga** [comment]
Works nicely now
