### ISSUE TITLE
Unhandled exception when editing config.

### ISSUE THREAD

**Issue by Deaquay** [wiresock/WireSockUI#50]
Has ben since version 0.2.1.
Whenever I press the edit button the config pops up as expected. But the moment I type anything in the edit box I get Unhandled exception.
I click anywhere and press a keyboard button and the exception pops up and prompts for continue or exit.

If I press continue the colour styling is removed and then I can start typing without problems. Exit exits app.

Typing what I want to insert or edit elsewhere and copy pasting it into the edit box works though.

Here is the exception and how it looks when error removes colour from the text:

![image](https://github.com/wiresock/WireSockUI/assets/103206423/417b40bc-c1fc-4b7f-8994-05a4e2b95b73)

https://gist.githubusercontent.com/Deaquay/f8e68f0cfd1f0beab037b14a5f32994a/raw/c3b091b5ca2412a85f11a1d1b31cf2e75aa12e13/gistfile1.txt

**Comment by wiresock** [comment]
The issue you mentioned has been addressed in version 0.2.5. I encourage you to test this version and see if it resolves the problem for you. Your feedback on this update would be greatly appreciated.

**Comment by Deaquay** [comment]
Will do now

**Comment by Deaquay** [comment]
Works perfectly now, thanks! Love your work :)
