### ISSUE TITLE
Torrents not working with versions after v0.1.13 

### ISSUE THREAD

**Issue by scrollop** [wiresock/WireSockUI#51]
Love the program - was working well (config excluded LAN traffic and a few programs eg chrome, whilst firefox ran through the VPN and could be tested by checking myIP in both, and qbitorrent traffic was tied to the VPN connection and worked as expected) until [v0.2.1] and with each version including [v0.2.5] when:

1) The split continued to work for firefox and chrome ie web browsing

2) Qbitorrent can not make connections  - "Connection status offline"

3) LAN traffic continues to be bypassed and SMB shares can still be accessed by a different LAN computer

To test this, wiresockui was closed,  [v0.1.13] was copied into the program folder and WireSockUI was restarted -->

Qbitorrent quickly was able to make connections as normal.

Version [v0.2.5] was again copied over and the qbitorrent again stated: "connection status offline"..
Thus, it appears the newer versions are doing something to qbitorrent traffic,

**Comment by wiresock** [comment]
To provide you with precise assistance, I require more details about your current setup. Could you specify which version of the WireSock VPN Client is installed on your system? WireSockUI acts as the front-end interface for it. The method of launching WireSockUI—whether as an administrator or a regular user—is significant. It's important to note that starting from version 0.2.1, WireSockUI can operate under a non-admin user. However, this mode has certain limitations, such as the unavailability of the virtual adapter mode. Initially, WireSockUI attempts to elevate its privileges to admin level. If this access is denied by you, it will continue functioning with non-administrative privileges.

**Comment by scrollop** [comment]
It was version 1.2.30.1 so  I upgraded to 1.2.37.1 just now and kept the UI the same, and then qbitorrent stopped working (same issue as when the UI is updated).

I updated the UI to the latest, and qbitorrent still couldn't connect, so I downgraded wiresock client back to 1.2.30.1, qbitorrent still didn't work, so I downgraded the client back to 0.1.13 and now qbitorrent won't connect.

It seems upgrading the wiresock client has done something :/

**Comment by wiresock** [comment]
There have been some ABI changes, which might affect the compatibility of the components. To address this, please uninstall WireSock VPN Client and **reboot** your system. After the reboot, reinstall the latest version and try using it with the latest version of WireSockUI.

**Comment by scrollop** [comment]
> There have been some ABI changes, which might affect the compatibility of the components. To address this, please uninstall WireSock VPN Client and **reboot** your system. After the reboot, reinstall the latest version and try using it with the latest version of WireSockUI.

I did that, installed both updated versions, changed the bound connection in qbitorrent advanced settings and everything works,  thank you.
