### ISSUE TITLE
Error at Startup - Wiresock Client Not Installed

### ISSUE THREAD

**Issue by TracyPeterson** [wiresock/WireSockUI#61]
am getting this error "WireSock VPN Client" needs to be installed for WireSockUI to function".  

I have uninstalled the wiresock client but cannot find where to disable this check or to remove wiresockui at all.  There is no uninstall hook in windows.

**Comment by wiresock** [comment]
This message originates from WireSockUI; as such, just refrain from starting it or delete it from disk.
