### ISSUE TITLE
Install command crashes on Windows 7

### ISSUE THREAD

**Issue by movsar** [wiresock/WireSockUI#63]
When I try to install the service using something like this:
`wiresock-client install -start-type 2 -account admin -password pass -config c:\wg.conf`
It crashes with this error:
`CreateService failed with error code: 0x00000421`

* I played with the input and it results in this error with any account and password given
* When called without account/password, it says it installed the service, but it really doesn't do anything
* After googling I thought it's a permissions issue and enabled the Administrator account and tried with it - the same output

**Comment by wiresock** [comment]
Are these valid user credentials? Please note that the application will not create a new user. Are you running this command as an Administrator?
